version: '3.8'

services:
  crud-app:
    build: .
    container_name: crud-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/cruddb;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_ENABLED: false

      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    volumes:
      - ./docker-data:/app/data
    restart: unless-stopped